server:
  port: 8888
spring:
  mail:
    host: smtp.163.com
    username:
    password:
    properties:
      from:
sentry:
  dsn:
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0